services:
  - type: web
    name: indiezone
    env: node
    branch: main
    startCommand: node .output/server/index.mjs
    buildCommand: npm install && npm run build
    envVars:
    - key: NITRO_PRESET
      value: render-com
    - key: SUPABASE_URL
      value: https://kklreqfmfnevrdrnbmnb.supabase.co
    - key: SUPABASE_KEY
      value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtrbHJlcWZtZm5ldnJkcm5ibW5iIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NTU4MTIwNjIsImV4cCI6MTk3MTM4ODA2Mn0.9UNv1-ImVAYYS4hkNbDf7mga3HJQDgezn4vJsrQL03E
