name = "playground"
main = "./.output/server/index.mjs"
workers_dev = true
compatibility_date = "2022-09-10"
account_id = "c68eca73e742d200deae4eb492654f9a"
route = "indiezone.de"

[site]
bucket = ".output/public"
